name: Discord Notification

on:
  # Trigger on push and pull request events
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # You can also trigger on workflow completion
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  discord-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: |
            🔔 New ${{ github.event_name }} event in **${{ github.repository }}**
            
            **Branch:** ${{ github.ref_name }}
            **Status:** ${{ job.status }}
            **Triggered by:** ${{ github.actor }}
            
            [View Details](${{ github.event.head_commit.url || github.event.pull_request.html_url }})
